# backend/app/src/models/notifications/notification.py

"""
SQLAlchemy model for Notifications sent to users.
"""

import logging
from typing import Optional, TYPE_CHECKING, Dict, Any, List # Added List for delivery_attempts
from datetime import datetime, timezone, timedelta # Added timezone, timedelta for __main__

from sqlalchemy import ForeignKey, Text, Boolean, DateTime, String, JSON, Integer # Added Integer for FKs
from sqlalchemy.orm import Mapped, mapped_column, relationship
# from sqlalchemy.sql import func # Not strictly needed here as created_at from BaseModel has server_default

from backend.app.src.models.base import BaseModel
# from backend.app.src.core.dicts import NotificationType # Using string for notification_type_code for flexibility

# Configure logger for this module
logger = logging.getLogger(__name__)

if TYPE_CHECKING:
    from backend.app.src.models.auth.user import User
    from backend.app.src.models.notifications.delivery import NotificationDeliveryAttempt
    # from backend.app.src.models.dictionaries.messengers import MessengerPlatform # If type code links to this
    # from backend.app.src.models.dictionaries.notification_types import NotificationTypeDict # If using a dict table for notification_type_code

class Notification(BaseModel):
    """
    Represents a notification generated by the system to be delivered to a user.

    Attributes:
        user_id (int): Foreign key to the user who is the recipient of this notification.
        notification_type_code (str): A code representing the type of notification
                                     (e.g., 'TASK_ASSIGNED', 'BONUS_AWARDED', from core.dicts.NotificationType or a dictionary table).
        message_payload (Optional[Dict]): JSON field to store the content/payload of the notification,
                                        which can be structured for rendering on different channels.
                                        Can include title, body, data, etc.
        is_read (bool): Whether the user has marked this notification as read.
        read_at (Optional[datetime]): Timestamp when the notification was marked as read.
        link_to_entity_type (Optional[str]): Type of entity this notification links to (e.g., 'task', 'group', 'reward').
        link_to_entity_id (Optional[int]): ID of the linked entity.
        expires_at (Optional[datetime]): Optional time when this notification is no longer relevant or should be hidden.
        # `id`, `created_at` (notification generation time), `updated_at` from BaseModel.
    """
    __tablename__ = "notifications"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("users.id"), nullable=False, index=True, comment="FK to the user recipient of the notification")

    notification_type_code: Mapped[str] = mapped_column(String(100), nullable=False, index=True, comment="Code identifying the type of notification (e.g., 'TASK_ASSIGNED')")
    # Consider FK to dict_notification_types.code if such a table exists and codes are managed there.

    # Storing message content as JSON allows for rich, structured notifications.
    # Simple text messages could just use a 'body' key within this JSON.
    message_payload: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True, comment="JSON payload with notification content (e.g., title, body, data)")

    is_read: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True, comment="Has the user read this notification?")
    read_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True, comment="Timestamp when the notification was marked as read (UTC)")

    link_to_entity_type: Mapped[Optional[str]] = mapped_column(String(100), nullable=True, index=True, comment="Type of entity this notification links to (e.g., 'task', 'group')")
    link_to_entity_id: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, index=True, comment="ID of the linked entity")

    expires_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True, index=True, comment="Optional time when this notification expires or becomes irrelevant (UTC)")

    # --- Relationships ---
    user_recipient: Mapped["User"] = relationship(back_populates="notifications") # Renamed from 'user' to be more specific
    delivery_attempts: Mapped[List["NotificationDeliveryAttempt"]] = relationship(back_populates="notification", cascade="all, delete-orphan")

    # If notification_type_code were a FK:
    # notification_type: Mapped["NotificationTypeDict"] = relationship(foreign_keys=[notification_type_code_fk_if_any])

    def __repr__(self) -> str:
        id_val = getattr(self, 'id', 'N/A')
        return f"<Notification(id={id_val}, user_id={self.user_id}, type='{self.notification_type_code}', is_read={self.is_read})>"

if __name__ == "__main__":
    if not logging.getLogger().hasHandlers():
        logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    logger.info("--- Notification Model --- Demonstration")

    # Example Notification instance
    # Assume User id=1 exists
    notif1 = Notification(
        user_id=1,
        notification_type_code="TASK_REMINDER",
        message_payload={
            "title": "Task Due Soon!",
            "body": "Your task 'Submit Monthly Report' is due in 24 hours.",
            "actions": [{"label": "View Task", "link_key": "view_task"}]
        },
        is_read=False,
        link_to_entity_type="task",
        link_to_entity_id=101, # Assuming task with id=101
        expires_at=datetime.now(timezone.utc) + timedelta(days=2)
    )
    notif1.id = 1 # Simulate ORM-set ID
    notif1.created_at = datetime.now(timezone.utc)
    notif1.updated_at = datetime.now(timezone.utc)

    logger.info(f"Example Notification: {notif1!r}")
    logger.info(f"  User ID: {notif1.user_id}, Type: {notif1.notification_type_code}")
    logger.info(f"  Payload: {notif1.message_payload}")
    logger.info(f"  Is Read: {notif1.is_read}")
    logger.info(f"  Links to: {notif1.link_to_entity_type} ID {notif1.link_to_entity_id}")
    logger.info(f"  Expires At: {notif1.expires_at.isoformat() if notif1.expires_at else 'N/A'}")
    logger.info(f"  Created At: {notif1.created_at.isoformat() if notif1.created_at else 'N/A'}")


    notif2_bonus = Notification(
        user_id=2, # User 2
        notification_type_code="BONUS_AWARDED",
        message_payload={"title": "Bonus Awarded!", "body": "You received 50 points for excellent work!"},
        is_read=True,
        read_at=datetime.now(timezone.utc) - timedelta(hours=1)
    )
    notif2_bonus.id = 2
    logger.info(f"Example Read Notification: {notif2_bonus!r}")

    # The following line would error if run directly without SQLAlchemy engine and metadata setup for all related tables.
    # logger.info(f"Notification attributes (conceptual table columns): {[c.name for c in Notification.__table__.columns if not c.name.startswith('_')]}")
    logger.info("To see actual table columns, SQLAlchemy metadata needs to be initialized with an engine (e.g., Base.metadata.create_all(engine)).")
