# backend/app/src/models/system/monitoring.py

"""
SQLAlchemy models for system monitoring, including logs and performance metrics.
"""

import logging
from typing import Optional, Dict, Any # Added Any for Dict value type
from datetime import datetime, timezone # Used in type hint for created_at from BaseModel and __main__

from sqlalchemy import String, Text, JSON, Float, Index, Integer # Added Integer for SystemLog.line_no
from sqlalchemy.orm import Mapped, mapped_column

from backend.app.src.models.base import BaseModel # Import your base model

# Configure logger for this module
logger = logging.getLogger(__name__)

class SystemLog(BaseModel):
    """
    Represents a log entry generated by the system or application.
    Useful for auditing, debugging, and tracking events.

    Attributes:
        level (str): Log level (e.g., INFO, WARNING, ERROR, DEBUG, CRITICAL).
        message (str): The main log message.
        logger_name (Optional[str]): The name of the logger that produced this entry (e.g., 'auth.service', 'tasks.scheduler').
        module (Optional[str]): The Python module where the log originated.
        func_name (Optional[str]): The function name where the log originated.
        line_no (Optional[int]): The line number where the log originated.
        exception_info (Optional[str]): Traceback information if the log entry is associated with an exception.
        context (Optional[Dict]): Additional contextual information stored as JSON (e.g., user_id, request_id, relevant data).
        # `created_at` from BaseModel will serve as the timestamp.
    """
    __tablename__ = "system_logs"

    level: Mapped[str] = mapped_column(String(50), nullable=False, index=True, comment="Log level (e.g., INFO, WARNING)")
    message: Mapped[str] = mapped_column(Text, nullable=False, comment="The main log message")
    logger_name: Mapped[Optional[str]] = mapped_column(String(255), index=True, comment="Name of the logger (e.g., module path)")
    module: Mapped[Optional[str]] = mapped_column(String(255), comment="Module where the log originated")
    func_name: Mapped[Optional[str]] = mapped_column(String(255), comment="Function name where the log originated")
    line_no: Mapped[Optional[int]] = mapped_column(Integer, comment="Line number of the log statement")
    exception_info: Mapped[Optional[str]] = mapped_column(Text, nullable=True, comment="Stack trace if an exception was logged") # Made nullable=True
    context: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True, comment="Additional contextual JSON data")

    # Add an index on created_at (from BaseModel) as logs are often queried by time
    # Also index level and logger_name for common filtering
    __table_args__ = (
        Index('ix_system_logs_created_at', 'created_at'),
        Index('ix_system_logs_level', 'level'),
        Index('ix_system_logs_logger_name', 'logger_name'),
    )

    def __repr__(self) -> str:
        # Ensure id exists for repr, or handle its absence
        id_val = getattr(self, 'id', 'N/A')
        return f"<SystemLog(id={id_val}, level='{self.level}', logger='{self.logger_name}', message='{self.message[:50]}...')>"

class PerformanceMetric(BaseModel):
    """
    Represents a recorded performance metric from the application.
    Useful for monitoring system health, response times, resource usage, etc.

    Attributes:
        metric_name (str): Name of the metric (e.g., 'api_response_time', 'db_query_duration', 'cpu_usage_percent').
        value (float): The value of the metric.
        unit (Optional[str]): Unit of the metric (e.g., 'ms', 'seconds', '%', 'count').
        tags (Optional[Dict]): Key-value pairs for additional context or dimensions (e.g., {'endpoint': '/users', 'method': 'GET'}).
        # `created_at` from BaseModel will serve as the timestamp of when the metric was recorded.
    """
    __tablename__ = "performance_metrics"

    metric_name: Mapped[str] = mapped_column(String(255), nullable=False, index=True, comment="Name of the performance metric")
    value: Mapped[float] = mapped_column(Float, nullable=False, comment="Value of the metric")
    unit: Mapped[Optional[str]] = mapped_column(String(50), nullable=True, comment="Unit of the metric (e.g., ms, %, count)") # Made nullable=True
    tags: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True, comment="Key-value tags for metric dimensions")

    # Add indexes for common query patterns
    __table_args__ = (
        Index('ix_performance_metrics_metric_name_created_at', 'metric_name', 'created_at'),
    )

    def __repr__(self) -> str:
        id_val = getattr(self, 'id', 'N/A')
        return f"<PerformanceMetric(id={id_val}, name='{self.metric_name}', value={self.value}, unit='{self.unit}')>"

if __name__ == "__main__":
    # This block is for demonstration and basic testing of model structures.
    if not logging.getLogger().hasHandlers():
        logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    logger.info("--- System Monitoring Models --- Demonstration")

    # SystemLog example
    log_entry = SystemLog(
        level="INFO",
        message="User 'john_doe' logged in successfully.",
        logger_name="auth_service",
        module="backend.app.src.services.auth.login",
        func_name="authenticate_user",
        line_no=152,
        context={"user_id": 123, "ip_address": "192.168.1.100"}
    )
    # In a real scenario, created_at and updated_at would be set by the DB or ORM
    # For __main__ demo, we simulate these being set.
    log_entry.created_at = datetime.now(timezone.utc)
    log_entry.updated_at = datetime.now(timezone.utc)
    log_entry.id = 1 # Simulate an ID for repr
    logger.info(f"Example SystemLog: {log_entry!r}")
    logger.info(f"  Log context: {log_entry.context}")

    # PerformanceMetric example
    metric_entry = PerformanceMetric(
        metric_name="api_response_time",
        value=125.5,
        unit="ms",
        tags={"endpoint": "/api/v1/items", "method": "POST"}
    )
    metric_entry.created_at = datetime.now(timezone.utc)
    metric_entry.updated_at = datetime.now(timezone.utc)
    metric_entry.id = 1 # Simulate an ID for repr
    logger.info(f"Example PerformanceMetric: {metric_entry!r}")
    logger.info(f"  Metric tags: {metric_entry.tags}")

    # The following lines would error if run directly without SQLAlchemy engine and metadata setup.
    # They are here for illustrative purposes of what could be inspected.
    # logger.info(f"SystemLog attributes (conceptual table columns): {[c.name for c in SystemLog.__table__.columns if not c.name.startswith('_')]}")
    # logger.info(f"PerformanceMetric attributes (conceptual table columns): {[c.name for c in PerformanceMetric.__table__.columns if not c.name.startswith('_')]}")
    logger.info("To see actual table columns, SQLAlchemy metadata needs to be initialized with an engine (e.g., Base.metadata.create_all(engine)).")
